"""Pull periodic GWL measurements for the BC 2027 network wells directly from
the DWR CKAN datastore SQL API.

We send one SQL query that filters by `site_code IN (...)` for the 77 resolved
site_codes, paginated through CKAN's `datastore_search_sql` endpoint. This is
far faster than downloading the ~2 GB state-wide measurements.csv.

Output:
    - js/measurements-data.js          (MEASUREMENTS dict for the dashboard)

Run this whenever you want fresh DWR data — no daily-build infra required for
the local static dashboard.
"""
import json
import sys
import time
import urllib.parse
from datetime import datetime, timezone
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parent.parent
WELLS_JSON = ROOT / "data" / "wells_resolved.json"
OUT_JS = ROOT / "js" / "measurements-data.js"
RESOURCE_ID = "bfa9f262-24a1-45bd-8dc8-138bc8107266"

CKAN_SQL = "https://data.cnra.ca.gov/api/3/action/datastore_search_sql"
CKAN_SEARCH = "https://data.cnra.ca.gov/api/3/action/datastore_search"
PAGE_SIZE = 32000   # CKAN max is 32000 records per call


def fetch_for_sites(site_codes: list[str]) -> list[dict]:
    """Fetch all measurement rows where site_code is one of `site_codes`.

    Strategy: per-site query (PAGE_SIZE/site is huge, fewer-and-cleaner than
    a single SQL-with-IN that might exceed URL limits).
    """
    rows = []
    for i, sc in enumerate(site_codes, 1):
        offset = 0
        site_rows = 0
        while True:
            params = {
                "resource_id": RESOURCE_ID,
                "filters": json.dumps({"site_code": sc}),
                "limit": PAGE_SIZE,
                "offset": offset,
            }
            url = CKAN_SEARCH + "?" + urllib.parse.urlencode(params)
            r = requests.get(url, timeout=60)
            r.raise_for_status()
            j = r.json()
            if not j.get("success"):
                raise SystemExit(f"CKAN error for {sc}: {j}")
            recs = j["result"]["records"]
            rows.extend(recs)
            site_rows += len(recs)
            if len(recs) < PAGE_SIZE:
                break
            offset += PAGE_SIZE
        print(f"  [{i:>3}/{len(site_codes)}] {sc}  +{site_rows:>5} rows")
    return rows


def main():
    wells = json.loads(WELLS_JSON.read_text())
    sites = sorted({w["site_code"] for w in wells if w.get("site_code")})
    print(f"Pulling measurements for {len(sites)} site_codes")
    t0 = time.time()
    rows = fetch_for_sites(sites)
    print(f"\nGot {len(rows):,} rows total in {time.time()-t0:.1f}s")

    # Group into MEASUREMENTS dict
    by_site: dict[str, dict[str, dict]] = {}
    for r in rows:
        sc = r.get("site_code")
        if not sc:
            continue
        d = (r.get("msmt_date") or "")[:10]
        if not d:
            continue
        try:
            gwe = float(r["gwe"]) if r.get("gwe") not in (None, "") else None
        except (TypeError, ValueError):
            gwe = None
        try:
            dtw = float(r["gse_gwe"]) if r.get("gse_gwe") not in (None, "") else None
        except (TypeError, ValueError):
            dtw = None
        qa = r.get("wlm_qa_desc") or ""
        by_site.setdefault(sc, {})[d] = {"d": d, "gwe": gwe, "dtw": dtw, "qa": qa}

    out = {}
    n_records = 0
    n_wells = 0
    for sc, recs in by_site.items():
        sorted_recs = [recs[k] for k in sorted(recs)]
        if not sorted_recs:
            continue
        out[sc] = sorted_recs
        n_records += len(sorted_recs)
        n_wells += 1

    print(f"\nWells with data: {n_wells}/{len(sites)}")
    print(f"Total dedup'd records: {n_records:,}")

    print("\nRMS coverage:")
    rms = [w for w in wells if w["is_2027_gwl_rms"]]
    for w in rms:
        sc = w["site_code"]
        recs = out.get(sc, [])
        n = len(recs)
        first = recs[0]["d"] if recs else "—"
        last = recs[-1]["d"] if recs else "—"
        print(f"  {w['swn_or_name']:24}  n={n:>5}  {first}  ->  {last}")

    meta = {
        "fetched_at": datetime.now(tz=timezone.utc).isoformat(),
        "n_records": n_records,
        "n_wells": n_wells,
        "source": "DWR CKAN datastore_search; resource " + RESOURCE_ID,
    }

    OUT_JS.parent.mkdir(parents=True, exist_ok=True)
    with OUT_JS.open("w") as f:
        f.write("// Auto-generated by scripts/fetch_dwr_measurements.py - do not edit by hand.\n")
        f.write("// Source: DWR CKAN periodic groundwater level Measurements (filtered to network wells).\n\n")
        f.write("const MEASUREMENTS_META = " + json.dumps(meta) + ";\n")
        f.write("const MEASUREMENTS = " + json.dumps(out) + ";\n")
    print(f"\nWrote {OUT_JS} ({OUT_JS.stat().st_size/1e6:.1f} MB)")


if __name__ == "__main__":
    main()
