"""Fetch the Sacramento Valley Water Year Index and emit js/wy-index-data.js.

Source: DWR CDEC "Water Year Hydrologic Classification Indices" report
(WSIHIST) — the official "40-30-30" Sacramento Valley Index, water years
1906-present, classifying each water year (Oct 1 - Sep 30) as:

    W  = Wet
    AN = Above Normal
    BN = Below Normal
    D  = Dry
    C  = Critical

The dashboard uses this to shade Dry and Critical water years on the §5.3
hydrograph and to split the LML trigger-frequency readout into drought vs
non-drought years. The Sacramento Valley Index is the correct index for the
Vina Subbasin (northern Sacramento Valley; the Feather River, which borders
the subbasin, is one of the index's four component rivers). The San Joaquin
columns in the same WSIHIST row are deliberately ignored.

WSIHIST row format (the full classification table):
    YEAR  Oct-Mar  Apr-Jul  WYsum  Index  Yr-type   <SanJoaquin: 4 cols + Yr-type>
    1977    2.49     1.93    5.12   3.11    C          0.22  0.80  1.05  0.84  C
                                            ^^^ Sacramento Yr-type = field[5]

Run:
    python3 scripts/fetch_wy_index.py     # -> js/wy-index-data.js

Refresh annually — the current (in-progress) water year is provisional until
DWR's final May B120 determination.
"""
import datetime
import json
import re
import ssl
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "js" / "wy-index-data.js"
URL = "https://cdec.water.ca.gov/reportapp/javareports?name=WSIHIST"

VALID_CLASSES = {"W", "AN", "BN", "D", "C"}
# Known-good anchors — if the parse drifts (e.g. accidentally reads the San
# Joaquin column, or the table layout changes), fail loudly instead of
# silently shipping wrong drought shading.
ANCHORS = {1976: "C", 1977: "C", 1983: "W", 2015: "C", 2017: "W"}


def fetch() -> str:
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    req = urllib.request.Request(URL, headers={"User-Agent": "Mozilla/5.0"})
    return urllib.request.urlopen(req, timeout=60, context=ctx).read().decode("utf-8", "replace")


def parse(html: str) -> dict:
    """Parse the full Sacramento Valley classification table.

    A data row is: 4-digit year, then 4 floats (Sac Oct-Mar / Apr-Jul /
    WYsum / Index), then the Sac Yr-type letter code, then 4 more floats and
    the San Joaquin Yr-type. We key on that exact shape so the abbreviated
    summary tables elsewhere in the report (year + 1 float + code) don't match.
    """
    row_re = re.compile(
        r"^\s*(\d{4})\s+"
        r"([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+"   # 4 Sac floats
        r"(W|AN|BN|D|C)\b"                                  # Sac Yr-type
    )
    out = {}
    for line in html.splitlines():
        m = row_re.match(line)
        if not m:
            continue
        year = int(m.group(1))
        if not (1900 <= year <= 2100):
            continue
        cls = m.group(6)
        index_val = float(m.group(5))
        # Guard against the second-half San-Joaquin columns being misread:
        # the Sac index float must be a plausible index (0-40).
        if cls not in VALID_CLASSES:
            continue
        out[year] = {"index": round(index_val, 2), "class": cls}
    return out


def main():
    html = fetch()
    wy = parse(html)
    if not wy:
        raise SystemExit("Parsed 0 water years — WSIHIST layout may have changed.")

    for year, expected in ANCHORS.items():
        got = wy.get(year, {}).get("class")
        if got != expected:
            raise SystemExit(
                f"ANCHOR FAILED: WY{year} expected {expected!r}, got {got!r}. "
                "Parse drifted (San Joaquin column? layout change?) — not writing output."
            )

    years = sorted(wy)
    first, last = years[0], years[-1]
    retrieved = datetime.date.today().isoformat()
    # The in-progress water year (and any beyond DWR's final determination)
    # is provisional. Today's water year = calendar year + 1 if month >= Oct.
    today = datetime.date.today()
    current_wy = today.year + (1 if today.month >= 10 else 0)
    provisional = [y for y in years if y >= current_wy]

    n_dry = sum(1 for y in wy.values() if y["class"] == "D")
    n_crit = sum(1 for y in wy.values() if y["class"] == "C")

    header = (
        "// Auto-generated by scripts/fetch_wy_index.py - do not edit by hand.\n"
        f"// Source: DWR CDEC WSIHIST (Sacramento Valley 40-30-30 Water Year Index).\n"
        f"//   {URL}\n"
        f"// Retrieved: {retrieved}. Water years {first}-{last} "
        f"({len(years)} years; {n_dry} Dry, {n_crit} Critical).\n"
        "// Class codes: W=Wet, AN=Above Normal, BN=Below Normal, D=Dry, C=Critical.\n"
        "// `index` is the Sacramento Valley 40-30-30 index value ( float).\n"
    )
    if provisional:
        header += (
            f"// PROVISIONAL: WY {', '.join(map(str, provisional))} "
            "is in-progress / not yet final (DWR finalizes at the May B120). "
            "Re-run this script annually to refresh.\n"
        )

    OUT.write_text(header + "\nconst WY_INDEX = " + json.dumps(wy) + ";\n")
    print(f"Wrote {OUT}")
    print(f"  water years: {first}-{last} ({len(years)})")
    print(f"  Dry: {n_dry}   Critical: {n_crit}")
    if provisional:
        print(f"  provisional: {provisional}")
    print("  anchors OK:", ", ".join(f"{y}={c}" for y, c in ANCHORS.items()))


if __name__ == "__main__":
    main()
